ALTER TABLE "Goal"
ADD COLUMN "metricUnit" TEXT,
ADD COLUMN "metricTarget" DOUBLE PRECISION,
ADD COLUMN "metricCurrent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "remindersEnabled" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Action"
ADD COLUMN "reminderEnabled" BOOLEAN NOT NULL DEFAULT true;
